[project]
name = "fastapi-url-shortener"
version = "0.1.0"
description = "FatAPI URL Shortener"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=26.1.0",
    "fastapi[standard]>=0.116.2",
]
